notifications:
  email: false

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

service:
- docker

addons:
  apt:
    packages:
    - bash
    - curl
    - docker-ce

install: true
before_install:
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install docker-compose httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null

script:
- export root=$(pwd)
- ./mvnw >/dev/null
- java -Djava.net.preferIPv4Stack=true -jar ./target/*-swarm.jar &
- wait_for 8080
- http :8080/api/v1/statistics
- http :8080/api/v1/messages message=ololo
- http :8080/api/v1/messages message=trololo
- http :8080/api/v1/messages
- http :8080/api/v1/statistics
- stop_any 8080
##DO NOT USE GRADLE, WILDFLY-SWARM HAS A LOT OF ISSUES...
#- ./gradlew >/dev/null
#- ./build/libs/*-swarm.jar &
#- wait_for 8080
#- http :8080/api/v1/messages message=trololo
#- http :8080/api/v1/messages message=ololo
#- http :8080/api/v1/messages
#- stop_any 8080

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

cache:
  directories:
  - $HOME/.m2
  - $HOME/.docker
  #- $HOME/.gradle
